First attempt
COSC3020/theory-vs-practice-howardthegr8one-1 pull request #2
Opened 2024-01-28 21:41 UTC by howardthegr8one

2024-01-29 20:30 UTC, larskotthoff requested changes

2024-01-29 20:30 UTC, larskotthoff commented on README.md
> +- The algorithm might be implemented in such a way that the slowness isn't apparent until the input size is large enough. For example a brute force implementation to solve the traveling salesperson p
But the asymptotic complexity tells us about exactly this case -- what happens when the input is large.

2024-01-29 20:30 UTC, larskotthoff commented on README.md
> +- The data structure the algorithm uses doesn't scale well with larger inputs. Even if the algorithm logically works, an ineffecient choice of data structure could be increasing the runtime beyond wh
But then it wouldn't have that asymptotic complexity.

2024-01-30 22:33 UTC, larskotthoff requested changes

2024-01-30 22:33 UTC, larskotthoff commented on README.md
> +- Our time estimate was based on our assumption that the runtime complexity is $log(n)$, however the actual time it takes to run could be slower than estimated due to a constant of some kind, perhaps
How would a constant factor change your estimate?

2024-02-03 19:43 UTC, larskotthoff requested changes

2024-02-03 19:43 UTC, larskotthoff commented on README.md
> +- Asymptotic analysis doesn't account for differences or limitations in hardware. Therefore you could have an algorithm with a seemingly fast asymptotic runtime that in practice can't make full use o
...but the asymptotic analysis we've been doing doesn't take parallelism into account at all.

2024-02-03 19:43 UTC, larskotthoff commented on README.md
> +- Similarly to the first question, our estimate was based on the asymptotic runtime complexity. Therefore since the algorithm is performing slower in practice there could be lower order terms or cons
But those would affect the run for the smaller input as well.

2024-02-03 19:43 UTC, larskotthoff commented on README.md
> +- Lastly the type of input could also account for such a large difference in our estimate compared to the actual runtime. For example when testing with $1,000$ elements the input could've been a best
Don't really see that -- how many more levels would a binary tree have doing from 1000 to 10000?

2024-03-22 18:03 UTC, closed without merging

2024-03-22 18:06 UTC, howardthegr8one commented
Not sure why but when I went back to the correct feedback branch it created a conflict between the branches, so I'm closing this one and just going back to the github classroom feedback branch for my work.